SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS USING (ANIMAL_ID)
WHERE (SEX_UPON_INTAKE LIKE 'Intact %' AND SEX_UPON_OUTCOME LIKE 'SPAYED %') OR (SEX_UPON_INTAKE LIKE 'Intact %' AND SEX_UPON_OUTCOME LIKE 'NEUTERED %')
ORDER BY ANIMAL_OUTS.ANIMAL_ID