SELECT CATEGORY, SUM(TS) AS TOTAL_SALES
FROM BOOK JOIN 
(SELECT BOOK_ID, SUM(SALES) AS TS
FROM BOOK_SALES
WHERE MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID)INS USING (BOOK_ID)
GROUP BY CATEGORY
ORDER BY 1 ASC
