SELECT ANIMAL_ID, NAME
,
CASE SEX_UPON_INTAKE WHEN 'NEUTERED MALE' THEN 'O'
                     WHEN 'SPAYED FEMALE' THEN 'O'
                     ELSE 'X' END AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID