SELECT PRODUCT_ID, PRODUCT_NAME, SS*PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT JOIN(
SELECT PRODUCT_ID, PRODUCE_DATE, SUM(AMOUNT) AS SS
FROM FOOD_ORDER WHERE MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID)AA USING (PRODUCT_ID)

ORDER BY 3 DESC, 1 ASC