SELECT REST_ID,REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO JOIN REST_REVIEW USING (REST_ID)
WHERE ADDRESS LIKE '서울시%' OR ADDRESS LIKE '서울특별시%'
GROUP BY REST_ID
ORDER BY 6 DESC, 4 DESC 

